version: "3.9"

services:
  #docker-gen:
  #  image: nginxproxy/docker-gen
  #  restart: always
  #  volumes:
  #    - /var/run/docker.sock:/tmp/docker.sock:ro
  #    - ./templates:/etc/docker-gen/templates
  #  labels:
  #    - com.github.nginx-proxy.docker-gen
  #  command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: no
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.nginx-proxy.nginx

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    volumes_from:
      - nginx-proxy:rw
    environment:
      - DEFAULT_EMAIL=me@carlucchese.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen

  #web-netjamco-legacy:
  #  image: netjamco:web-legacy
  #  restart: always
  ##  environment:
  #    - VIRTUAL_HOST=netjamco.es, www.netjamco.es
  #    - LETSENCRYPT_HOST=netjamco.es, www.netjamco.es
  #    - LETSENCRYPT_EMAIL=me@carlucchese.com
  #    - NETWORK_ACCESS=internal

volumes:
  acme:
  certs:
  vhost:
  html:
